#!/bin/sh

# Build a Container image with the DBT-5 Brokerage House.

PGVERSION=14.2

ENGINE="podman"
which podman > /dev/null 2>&1
if [ $? -ne 0 ]; then
	which $ENGINE > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "podman nor docker in path"
		exit 1
	fi
fi

if [ $# -ge 1 ]; then
	PGVERSION=$1
else
	which jq > /dev/null 2>&1
	if [ $? -eq 0 ]; then
		PGORG="https://www.postgresql.org/versions.json"
		PGVERSION=$(curl -s $PGORG | jq -r 'sort | .[] | "\(.major).\(.latestMinor)"' | tail -n 1)
	fi
fi

echo "Using PostgreSQL Major Version $PGVERSION"

TOPDIR=`dirname $0`

# Use the return code from `$ENGINE inspect` to determine if the $ENGINE image
# needs to be created.
$ENGINE inspect dbt5-base > /dev/null
if [ $? -ne 0 ]; then
	${TOPDIR}/prepare-image || exit 1
fi

if [ "$ENGINE" = "podman" ]; then
	PODMANARGS="--isolation=chroot"
fi

TOPDIR="${TOPDIR}/.."
$ENGINE build -t dbt5-driver \
		$PODMANARGS \
		--build-arg PGVERSION=$PGVERSION \
		-f Containerfile.common $TOPDIR
if [ $? -ne 0 ]; then
	echo "usage: $0 [DBMSVER]"
	echo
	exit 1
fi
