#!/bin/sh

# Prepare a Container image for building and running each component.

PGVERSION=14.2

ENGINE="podman"
which podman > /dev/null 2>&1
if [ $? -ne 0 ]; then
	which docker > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "podman nor docker in path"
		exit 1
	fi
fi

if [ $# -ne 1 ]; then
	which jq > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "install jq to automatically use the latest postgres version"
		echo "defaulting to version $PGVERSION"
	else
		PGORG="https://www.postgresql.org/versions.json"
		PGVERSION=`curl -s $PGORG | jq -r 'sort | .[].major' | tail -n 1`
	fi
else
	PGVERSION=$1
fi

echo "Using PostgreSQL Version $PGVERSION"

if [ "$ENGINE" = "podman" ]; then
	PODMANARGS="--isolation=chroot"
fi

CONTAINER_DIR=`dirname $0`
$ENGINE build \
		$PODMANARGS \
		-t dbt5-base \
		$CONTAINER_DIR
