#!/bin/sh

# Start the DBT-5 PostgreSQL database.

ENGINE="podman"
which podman > /dev/null 2>&1
if [ $? -ne 0 ]; then
	which $ENGINE > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "podman nor docker in path"
		exit 1
	fi
fi

SCALE=500
DBMS="pgsql"

if [ $# -ge 1 ]; then
	SCALE=$1
fi

if [ $# -ge 2 ]; then
	DBMS=$2
fi

CONTAINERDIR=$(dirname $0)
CONTAINER_TAG="dbt5-database-${DBMS}-${SCALE}s"
CONTAINER_NAME="dbt5-database-${DBMS}-${SCALE}s-0"

# Use the return code from `$ENGINE inspect` to determine if the container image
# needs to be created.
$ENGINE inspect $CONTAINER_TAG > /dev/null
if [ $? -ne 0 ]; then
	${CONTAINERDIR}/build-database $SCALE $DBMS || exit 1
fi

if [ "$ENGINE" = "podman" ]; then
	PODMANARGS="--network=podman"
fi

if [ "x$DBMS" = "xpgsql" ]; then
	PGDATA="/opt/pgdata"
	$ENGINE run \
			$PODMANARGS \
			-d --rm -u postgres:postgres --name $CONTAINER_NAME \
			-p 5432:5432 $CONTAINER_TAG postgres -D $PGDATA \
			-c client_encoding='SQL_ASCII' \
			-c listen_addresses='*' \
			-c unix_socket_directories='/tmp'
	RC=$?
else
	RC=1
fi
if [ $RC -ne 0 ]; then
	echo "usage: $0 [SCALE [DBMS]]"
	echo
	echo "DBMS options: (default: pgsql)"
	echo "  pgsql"
	exit 1
fi

which jq > /dev/null 2>&1
if [ $? -eq 0 ]; then
	IPADDRESS=$($ENGINE inspect $CONTAINER_NAME | jq -r '.[0].NetworkSettings.IPAddress')
	echo "IP Address: $IPADDRESS"
	echo "${CONTAINERDIR}/start-client $IPADDRESS $DBMS"
	if [ "x$DBMS" = "xpgsql" ]; then
		echo "psql -h $IPADDRESS dbt5 postgres"
	fi
else
	echo "Install jq for some tips the next time you run this script, or"
	echo "read the bottom of the file: $0"
fi
