#!/bin/sh

ENGINE="podman"
which podman > /dev/null 2>&1
if [ $? -ne 0 ]; then
	which $ENGINE > /dev/null 2>&1
	if [ $? -ne 0 ]; then
		echo "podman nor docker in path"
		exit 1
	fi
fi

if [ "$ENGINE" = "podman" ]; then
	export DBUS_SESSION_BUS_ADDRESS=""
fi

DOCKER_NAME="dbt5-driver-0"
EGENDIR="/usr/local/src/dbt5/egen"
$ENGINE exec -u postgres:postgres -it $DOCKER_NAME \
		MarketExchangeMain -c 5000 -t 5000 \
		-i ${EGENDIR}/flat_in -o /tmp
